cache:
  paths:
    - node_modules/
    - .yarn-cache

image: node

stages:
  - build-and-deploy

build-and-deploy:
  stage: build-and-deploy
  only:
    - master
  script:
    - yarn config set cache-folder .yarn-cache
    - yarn install --pure-lockfile
    - yarn build
    - ls -al build/
    - apt-get update -qq && apt-get install -y -qq lftp
    - lftp -e "set ftp:ssl-allow no; open $FTP_HOSTNAME; user $FTP_USERNAME $FTP_PASSWORD; mirror -X .* -X .*/ --reverse --verbose --delete build/ ./public_html; bye"
