/* GIFS ACTIONS */
const FETCH_HOME_GIFS_REQUEST = 'FETCH_HOME_GIFS_REQUEST';
const FETCH_HOME_GIFS_SUCCESS = 'FETCH_HOME_GIFS_SUCCESS';
const FETCH_HOME_GIFS_ERROR = 'FETCH_HOME_GIFS_ERROR';

const FETCH_FAV_GIFS_REQUEST = 'FETCH_FAV_GIFS_REQUEST';
const FETCH_FAV_GIFS_SUCCESS = 'FETCH_FAV_GIFS_SUCCESS';
const FETCH_FAV_GIFS_ERROR = 'FETCH_FAV_GIFS_ERROR';

export { 
    FETCH_HOME_GIFS_REQUEST, 
    FETCH_HOME_GIFS_SUCCESS, 
    FETCH_HOME_GIFS_ERROR,
    FETCH_FAV_GIFS_REQUEST,
    FETCH_FAV_GIFS_SUCCESS,
    FETCH_FAV_GIFS_ERROR 
}